"""empty message

Revision ID: 06c45ae5122f
Revises: c8098905892e
Create Date: 2022-05-19 16:57:21.761913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c45ae5122f'
down_revision = 'c8098905892e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_admin_test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_admin_test')
    # ### end Alembic commands ###