"""empty message

Revision ID: ba0671889dc4
Revises: 43ad8a0873e5
Create Date: 2022-05-14 14:51:28.619418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0671889dc4'
down_revision = '43ad8a0873e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('number_of_sanctions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('author', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('author', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('book', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('book', sa.Column('borrowed_date', sa.Date(), nullable=True))
    op.add_column('book', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book', 'account', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'user_id')
    op.drop_column('book', 'borrowed_date')
    op.drop_column('book', 'due_date')
    op.drop_column('book', 'price')
    op.alter_column('author', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('author', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('account')
    # ### end Alembic commands ###