"""empty message

Revision ID: c8098905892e
Revises: ba0671889dc4
Create Date: 2022-05-17 12:52:46.165203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8098905892e'
down_revision = 'ba0671889dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('book', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('book', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###